In [1]:
import pandas as pd
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [ ]:
heart_df = pd.read_csv("--file_path--")
heart_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3,30,No,Female,55-59,White,Yes,Yes,Very good,5,Yes,No,Yes
1,No,20.34,No,No,Yes,0,0,No,Female,80 or older,White,No,Yes,Very good,7,No,No,No
2,No,26.58,Yes,No,No,20,30,No,Male,65-69,White,Yes,Yes,Fair,8,Yes,No,No
3,No,24.21,No,No,No,0,0,No,Female,75-79,White,No,No,Good,6,No,No,Yes
4,No,23.71,No,No,No,28,0,Yes,Female,40-44,White,No,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7,0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6,Yes,No,No
319791,No,29.84,Yes,No,No,0,0,No,Male,35-39,Hispanic,No,Yes,Very good,5,Yes,No,No
319792,No,24.24,No,No,No,0,0,No,Female,45-49,Hispanic,No,Yes,Good,6,No,No,No
319793,No,32.81,No,No,No,0,0,No,Female,25-29,Hispanic,No,No,Good,12,No,No,No
319794,No,46.56,No,No,No,0,0,No,Female,80 or older,Hispanic,No,Yes,Good,8,No,No,No

In [3]:
heart_df.isna().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

In [4]:
heart_df.shape

(319795, 18)

In [4]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  object
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  object
 3   AlcoholDrinking   319795 non-null  object
 4   Stroke            319795 non-null  object
 5   PhysicalHealth    319795 non-null  int64
 6   MentalHealth      319795 non-null  int64
 7   DiffWalking       319795 non-null  object
 8   Sex               319795 non-null  object
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  Diabetic          319795 non-null  object
 12  PhysicalActivity  319795 non-null  object
 13  GenHealth         319795 non-null  object
 14  SleepTime         319795 non-null  int64
 15  Asthma            319795 non-null  object
 16  KidneyDisease     319795 non-null  object
 17  SkinCancer        319795 non-null  object
dtypes: float64(1), int64(3), object(14)
memory usage: 43.9+ MB

In [24]:
heart_df['Asthma'].value_counts()

Asthma
No     276923
Yes     42872
Name: count, dtype: int64

In [3]:
heart_df['HeartDisease'] = heart_df['HeartDisease'].map({'No':0,'Yes':1})
heart_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,16.60,Yes,No,No,3,30,No,Female,55-59,White,Yes,Yes,Very good,5,Yes,No,Yes
1,0,20.34,No,No,Yes,0,0,No,Female,80 or older,White,No,Yes,Very good,7,No,No,No
2,0,26.58,Yes,No,No,20,30,No,Male,65-69,White,Yes,Yes,Fair,8,Yes,No,No
3,0,24.21,No,No,No,0,0,No,Female,75-79,White,No,No,Good,6,No,No,Yes
4,0,23.71,No,No,No,28,0,Yes,Female,40-44,White,No,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,Yes,No,No,7,0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6,Yes,No,No
319791,0,29.84,Yes,No,No,0,0,No,Male,35-39,Hispanic,No,Yes,Very good,5,Yes,No,No
319792,0,24.24,No,No,No,0,0,No,Female,45-49,Hispanic,No,Yes,Good,6,No,No,No
319793,0,32.81,No,No,No,0,0,No,Female,25-29,Hispanic,No,No,Good,12,No,No,No
319794,0,46.56,No,No,No,0,0,No,Female,80 or older,Hispanic,No,Yes,Good,8,No,No,No

In [27]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  int64
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  int64
 3   AlcoholDrinking   319795 non-null  int64
 4   Stroke            319795 non-null  int64
 5   PhysicalHealth    319795 non-null  int64
 6   MentalHealth      319795 non-null  int64
 7   DiffWalking       319795 non-null  int64
 8   Sex               319795 non-null  int64
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  Diabetic          319795 non-null  object
 12  PhysicalActivity  319795 non-null  int64
 13  GenHealth         319795 non-null  object
 14  SleepTime         319795 non-null  int64
 15  Asthma            319795 non-null  int64
 16  KidneyDisease     319795 non-null  int64
 17  SkinCancer        319795 non-null  int64
dtypes: float64(1), int64(13), object(4)
memory usage: 43.9+ MB

In [ ]:
!pip install ydata_profiling

In [ ]:
from ydata_profiling import ProfileReport
ProfileReport(heart_df)

In [4]:
from sklearn.model_selection import train_test_split

X = heart_df.drop('HeartDisease', axis=1)
y = heart_df['HeartDisease']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
X_train.shape

(255836, 17)

In [30]:
X_test.shape

(63959, 17)

In [5]:
X_num = X_train.select_dtypes(include='number')
X_cat = X_train.select_dtypes(exclude='number')

In [18]:
X_num.columns

Index(['BMI', 'PhysicalHealth', 'MentalHealth', 'SleepTime'], dtype='object')

In [19]:
X_cat.columns

Index(['Smoking', 'AlcoholDrinking', 'Stroke', 'DiffWalking', 'Sex',
       'AgeCategory', 'Race', 'Diabetic', 'PhysicalActivity', 'GenHealth',
       'Asthma', 'KidneyDisease', 'SkinCancer'],
      dtype='object')

In [6]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.impute import SimpleImputer

# Categorical columns
cat_cols = X_cat.columns

# Numeric columns (all others)
num_cols = X_num.columns

# Numeric pipeline
num_pipe = Pipeline([
    ("scaler", StandardScaler())
])

# Categorical pipeline
cat_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

# Combine into preprocessor
preprocessor = ColumnTransformer([
    ("num", num_pipe, num_cols),
    ("cat", cat_pipe, cat_cols)
])

preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 Index(['BMI', 'PhysicalHealth', 'MentalHealth', 'SleepTime'], dtype='object')),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 Index(['Smoking', 'AlcoholDrinking', 'Stroke', 'DiffWalking', 'Sex',
       'AgeCategory', 'Race', 'Diabetic', 'PhysicalActivity', 'GenHealth',
       'Asthma', 'KidneyDisease', 'SkinCancer'],
      dtype='object'))])

In [17]:
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, recall_score, confusion_matrix

models_score = []

def test_model(model, X_train, X_test, y_train, y_test):
    pipe = Pipeline([
        ("prep", preprocessor),
        ("model", model)
    ])
    
    pipe.fit(X_train, y_train)
    preds = pipe.predict(X_test)

    acc = accuracy_score(y_test, preds)
    prec = precision_score(y_test, preds)
    rec = recall_score(y_test, preds)
    f1 = f1_score(y_test, preds)
    
    print("\n============================")
    print(model.__class__.__name__)
    print("============================")
    print(classification_report(y_test, preds))

    
    tn, fp, fn, tp = confusion_matrix(y_test, preds).ravel()
    print("Confusion Matrix:")
    print(f"TP={tp}, FN={fn}, FP={fp}, TN={tn}")
    print("Recall =", recall_score(y_test, preds))

    models_score.append({
            "Model": model.__class__.__name__,
            "Accuracy": acc,
            "Precision": prec,
            "Recall": rec,
            "F1 Score": f1
        })
    results_df = pd.DataFrame(models_score).sort_values(by="Recall", ascending=False).reset_index(drop=True)
    return results_df

In [22]:
X_train.select_dtypes(include='object').head()

,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,Asthma,KidneyDisease,SkinCancer
95877,Yes,No,No,No,Male,75-79,White,No,Yes,Very good,No,No,No
228939,Yes,No,Yes,No,Male,55-59,White,No,Yes,Good,No,No,No
260256,No,No,No,No,Male,50-54,Hispanic,No,No,Very good,No,No,No
84785,No,No,No,No,Female,25-29,White,No,Yes,Excellent,No,No,No
83845,Yes,No,No,No,Male,80 or older,White,Yes,Yes,Good,No,No,No

In [18]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(class_weight="balanced", max_iter=2000)
test_model(log_reg, X_train, X_test, y_train, y_test)

============================
LogisticRegression
============================
              precision    recall  f1-score   support

           0       0.97      0.75      0.84     58367
           1       0.23      0.78      0.35      5592

    accuracy                           0.75     63959
   macro avg       0.60      0.76      0.60     63959
weighted avg       0.91      0.75      0.80     63959

Confusion Matrix:
TP=4353, FN=1239, FP=14850, TN=43517
Recall = 0.7784334763948498

                Model  Accuracy  Precision    Recall  F1 Score
0  LogisticRegression  0.748448   0.226683  0.778433  0.351119

In [19]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=5, class_weight="balanced")
test_model(dt, X_train, X_test, y_train, y_test)

============================
DecisionTreeClassifier
============================
              precision    recall  f1-score   support

           0       0.95      0.78      0.86     58367
           1       0.21      0.60      0.31      5592

    accuracy                           0.76     63959
   macro avg       0.58      0.69      0.58     63959
weighted avg       0.89      0.76      0.81     63959

Confusion Matrix:
TP=3358, FN=2234, FP=12899, TN=45468
Recall = 0.6005007153075823

                    Model  Accuracy  Precision    Recall  F1 Score
0      LogisticRegression  0.748448   0.226683  0.778433  0.351119
1  DecisionTreeClassifier  0.763395   0.206557  0.600501  0.307382

In [20]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    class_weight="balanced",
    random_state=42
)
test_model(rf, X_train, X_test, y_train, y_test)

============================
RandomForestClassifier
============================
              precision    recall  f1-score   support

           0       0.97      0.76      0.85     58367
           1       0.23      0.74      0.35      5592

    accuracy                           0.76     63959
   macro avg       0.60      0.75      0.60     63959
weighted avg       0.90      0.76      0.81     63959

Confusion Matrix:
TP=4129, FN=1463, FP=13921, TN=44446
Recall = 0.7383762517882689

                    Model  Accuracy  Precision    Recall  F1 Score
0      LogisticRegression  0.748448   0.226683  0.778433  0.351119
1  RandomForestClassifier  0.759471   0.228753  0.738376  0.349294
2  DecisionTreeClassifier  0.763395   0.206557  0.600501  0.307382

In [21]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()
test_model(gb, X_train, X_test, y_train, y_test)

============================
GradientBoostingClassifier
============================
              precision    recall  f1-score   support

           0       0.92      0.99      0.95     58367
           1       0.55      0.09      0.15      5592

    accuracy                           0.91     63959
   macro avg       0.74      0.54      0.55     63959
weighted avg       0.89      0.91      0.88     63959

Confusion Matrix:
TP=497, FN=5095, FP=404, TN=57963
Recall = 0.08887696709585122

                        Model  Accuracy  Precision    Recall  F1 Score
0          LogisticRegression  0.748448   0.226683  0.778433  0.351119
1      RandomForestClassifier  0.759471   0.228753  0.738376  0.349294
2      DecisionTreeClassifier  0.763395   0.206557  0.600501  0.307382
3  GradientBoostingClassifier  0.914023   0.551609  0.088877  0.153088

In [22]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    eval_metric="logloss",
    max_depth=4,
    n_estimators=200,
    learning_rate=0.1
)
test_model(xgb, X_train, X_test, y_train, y_test)

============================
XGBClassifier
============================
              precision    recall  f1-score   support

           0       0.92      0.99      0.95     58367
           1       0.57      0.09      0.15      5592

    accuracy                           0.91     63959
   macro avg       0.74      0.54      0.55     63959
weighted avg       0.89      0.91      0.88     63959

Confusion Matrix:
TP=477, FN=5115, FP=363, TN=58004
Recall = 0.08530042918454936

                        Model  Accuracy  Precision    Recall  F1 Score
0          LogisticRegression  0.748448   0.226683  0.778433  0.351119
1      RandomForestClassifier  0.759471   0.228753  0.738376  0.349294
2      DecisionTreeClassifier  0.763395   0.206557  0.600501  0.307382
3  GradientBoostingClassifier  0.914023   0.551609  0.088877  0.153088
4               XGBClassifier  0.914351   0.567857  0.085300  0.148321

In [23]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report
import numpy as np

log_reg = LogisticRegression(class_weight="balanced", max_iter=5000)

pipe = Pipeline([
    ("prep", preprocessor),   # your preprocessor
    ("model", log_reg)
])

param_grid = {
    "model__C": [0.001, 0.01, 0.1, 1, 10],
    "model__penalty": ["l2"],
    "model__solver": ["liblinear", "lbfgs"]
}

grid = GridSearchCV(
    pipe,
    param_grid,
    scoring="recall",   # <-- important
    cv=3,
    n_jobs=-1
)

grid.fit(X_train, y_train)

print("Best Recall:", grid.best_score_)
print("Best Params:", grid.best_params_)

Best Recall: 0.7821035788896463
Best Params: {'model__C': 1, 'model__penalty': 'l2', 'model__solver': 'lbfgs'}