In [37]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [36]:
heart_df = pd.read_csv(".\data\heart_2020_cleaned.csv")
heart_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3,30,No,Female,55-59,White,Yes,Yes,Very good,5,Yes,No,Yes
1,No,20.34,No,No,Yes,0,0,No,Female,80 or older,White,No,Yes,Very good,7,No,No,No
2,No,26.58,Yes,No,No,20,30,No,Male,65-69,White,Yes,Yes,Fair,8,Yes,No,No
3,No,24.21,No,No,No,0,0,No,Female,75-79,White,No,No,Good,6,No,No,Yes
4,No,23.71,No,No,No,28,0,Yes,Female,40-44,White,No,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7,0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6,Yes,No,No
319791,No,29.84,Yes,No,No,0,0,No,Male,35-39,Hispanic,No,Yes,Very good,5,Yes,No,No
319792,No,24.24,No,No,No,0,0,No,Female,45-49,Hispanic,No,Yes,Good,6,No,No,No
319793,No,32.81,No,No,No,0,0,No,Female,25-29,Hispanic,No,No,Good,12,No,No,No
319794,No,46.56,No,No,No,0,0,No,Female,80 or older,Hispanic,No,Yes,Good,8,No,No,No

In [3]:
heart_df.isna().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

In [4]:
heart_df.shape

(319795, 18)

In [4]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  object
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  object
 3   AlcoholDrinking   319795 non-null  object
 4   Stroke            319795 non-null  object
 5   PhysicalHealth    319795 non-null  int64
 6   MentalHealth      319795 non-null  int64
 7   DiffWalking       319795 non-null  object
 8   Sex               319795 non-null  object
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  Diabetic          319795 non-null  object
 12  PhysicalActivity  319795 non-null  object
 13  GenHealth         319795 non-null  object
 14  SleepTime         319795 non-null  int64
 15  Asthma            319795 non-null  object
 16  KidneyDisease     319795 non-null  object
 17  SkinCancer        319795 non-null  object
dtypes: float64(1), int64(3), object(14)
memory usage: 43.9+ MB

In [63]:
heart_df['GenHealth'].value_counts()

GenHealth
Very good    113858
Good          93129
Excellent     66842
Fair          34677
Poor          11289
Name: count, dtype: int64

In [38]:
heart_df['HeartDisease'] = heart_df['HeartDisease'].map({'No':0,'Yes':1})
heart_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,16.60,Yes,No,No,3,30,No,Female,55-59,White,Yes,Yes,Very good,5,Yes,No,Yes
1,0,20.34,No,No,Yes,0,0,No,Female,80 or older,White,No,Yes,Very good,7,No,No,No
2,0,26.58,Yes,No,No,20,30,No,Male,65-69,White,Yes,Yes,Fair,8,Yes,No,No
3,0,24.21,No,No,No,0,0,No,Female,75-79,White,No,No,Good,6,No,No,Yes
4,0,23.71,No,No,No,28,0,Yes,Female,40-44,White,No,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,Yes,No,No,7,0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6,Yes,No,No
319791,0,29.84,Yes,No,No,0,0,No,Male,35-39,Hispanic,No,Yes,Very good,5,Yes,No,No
319792,0,24.24,No,No,No,0,0,No,Female,45-49,Hispanic,No,Yes,Good,6,No,No,No
319793,0,32.81,No,No,No,0,0,No,Female,25-29,Hispanic,No,No,Good,12,No,No,No
319794,0,46.56,No,No,No,0,0,No,Female,80 or older,Hispanic,No,Yes,Good,8,No,No,No

In [ ]:
heart_df.info()

In [ ]:
!pip install ydata_profiling

In [ ]:
from ydata_profiling import ProfileReport
ProfileReport(heart_df)

# Train-Test split

In [39]:
from sklearn.model_selection import train_test_split

X = heart_df.drop('HeartDisease', axis=1)
y = heart_df['HeartDisease']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
X_train.shape

(255836, 17)

In [30]:
X_test.shape

(63959, 17)

# Preprocessor with one-hot encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.impute import SimpleImputer

X_num = X_train.select_dtypes(include='number')
X_cat = X_train.select_dtypes(exclude='number')

# Categorical columns
cat_cols = X_cat.columns

# Numeric columns (all others)
num_cols = X_num.columns

# Numeric pipeline
num_pipe = Pipeline([
    ("scaler", StandardScaler())
])

# Categorical pipeline
cat_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

# Combine into preprocessor
preprocessor = ColumnTransformer([
    ("num", num_pipe, num_cols),
    ("cat", cat_pipe, cat_cols)
])

preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 Index(['BMI', 'PhysicalHealth', 'MentalHealth', 'SleepTime'], dtype='object')),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 Index(['Smoking', 'AlcoholDrinking', 'Stroke', 'DiffWalking', 'Sex',
       'AgeCategory', 'Race', 'Diabetic', 'PhysicalActivity', 'GenHealth',
       'Asthma', 'KidneyDisease', 'SkinCancer'],
      dtype='object'))])

# Preprocessor with both one-hot & ordinal encoding

In [70]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer


# -----------------------------
# 1. ORDINAL COLUMNS & CATEGORIES
# -----------------------------

ordinal_cols = ["AgeCategory", "GenHealth", "Diabetic"]

ordinal_categories = [

    # AgeCategory order
    ["18-24", "25-29", "30-34", "35-39", "40-44", "45-49",
     "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80 or older"],

    # GenHealth order
    ["Poor", "Fair", "Good", "Very good", "Excellent"],

    # Diabetic order
    ["No", "No, borderline diabetes", "Yes", "Yes (during pregnancy)"]
]


# -----------------------------
# 2. Nominal categorical columns
# -----------------------------

nominal_cols = [
    'Smoking', 'AlcoholDrinking', 'Stroke', 'DiffWalking', 'Sex',
    'Race', 'PhysicalActivity', 'Asthma',
    'KidneyDisease', 'SkinCancer'
]


# -----------------------------
# 3. Numeric columns
# -----------------------------

num_cols = ['BMI', 'PhysicalHealth', 'MentalHealth', 'SleepTime']


# -----------------------------
# 4. PIPELINES
# -----------------------------

# Numeric pipeline
num_pipe = Pipeline([
    ("scaler", StandardScaler())
])

# Ordinal pipeline
ordinal_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("ord", OrdinalEncoder(categories=ordinal_categories))
])

# Nominal pipeline
nominal_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])


# -----------------------------
# 5. COMBINED PREPROCESSOR
# -----------------------------

preprocessor = ColumnTransformer([
    ("num", num_pipe, num_cols),
    ("ord", ordinal_pipe, ordinal_cols),
    ("nom", nominal_pipe, nominal_cols)
])

preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 ['BMI', 'PhysicalHealth', 'MentalHealth',
                                  'SleepTime']),
                                ('ord',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('ord',
                                                  OrdinalEncoder(categories=[['18-24',
                                                                              '25-29',
                                                                              '30-34',
                                                                              '35-39',
                                                                              '40-44',
                                                                              '45-49',
                                                                              '50-54',
                                                                              '55-59',
                                                                              '60-64',
                                                                              '65-69',
                                                                              '70-74',
                                                                              '75-79',
                                                                              '80 '
                                                                              'o...
                                                                              'borderline '
                                                                              'diabetes',
                                                                              'Yes',
                                                                              'Yes '
                                                                              '(during '
                                                                              'pregnancy)']]))]),
                                 ['AgeCategory', 'GenHealth', 'Diabetic']),
                                ('nom',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['Smoking', 'AlcoholDrinking', 'Stroke',
                                  'DiffWalking', 'Sex', 'Race',
                                  'PhysicalActivity', 'Asthma', 'KidneyDisease',
                                  'SkinCancer'])])

# Function to test with different models

In [83]:
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, recall_score, confusion_matrix
from sklearn.feature_selection import SelectFromModel

models_score = []

def test_model(model, X_train, X_test, y_train, y_test, threshold=0.5):

    selector = SelectFromModel(
        RandomForestClassifier(n_estimators=200, random_state=42),
        threshold="median"      # keep features above median importance
    )

    pipe = Pipeline([
        ("prep", preprocessor),
        ("select", selector),
        ("model", model)
    ])
    
    pipe.fit(X_train, y_train)
      # ----------- NEW PART: prediction probability + threshold -----------
    probs = pipe.predict_proba(X_test)[:, 1]      # probability of class 1
    preds = (probs >= threshold).astype(int)      # convert to 0/1 based on threshold
    # -------------------------------------------------------------------

    acc = accuracy_score(y_test, preds)
    prec = precision_score(y_test, preds)
    rec = recall_score(y_test, preds)
    f1 = f1_score(y_test, preds)
    
    print("\n============================")
    print(model.__class__.__name__)
    print("============================")

    
    tn, fp, fn, tp = confusion_matrix(y_test, preds).ravel()
    print("Confusion Matrix:")
    print(f"TP={tp}, FN={fn}, FP={fp}, TN={tn}")
    print("Recall =", recall_score(y_test, preds))

    models_score.append({
            "Model": model.__class__.__name__,
            "Accuracy": acc,
            "Precision": prec,
            "Recall": rec,
            "F1 Score": f1
        })
    results_df = pd.DataFrame(models_score).sort_values(by="Recall", ascending=False).reset_index(drop=True)
    return results_df

In [84]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(class_weight="balanced", max_iter=5000, C = 0.1, penalty = 'l2', solver =  'liblinear')
test_model(log_reg, X_train, X_test, y_train, y_test, threshold=0.19)

============================
LogisticRegression
============================
Confusion Matrix:
TP=5402, FN=190, FP=36914, TN=21453
Recall = 0.9660228898426323

                Model  Accuracy  Precision    Recall  F1 Score
0  LogisticRegression  0.419878   0.127659  0.966023  0.225516

In [79]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=5, class_weight="balanced")
test_model(dt, X_train, X_test, y_train, y_test, threshold=0.19)

============================
DecisionTreeClassifier
============================
Confusion Matrix:
TP=5357, FN=235, FP=35233, TN=23134
Recall = 0.9579756795422032

                    Model  Accuracy  Precision    Recall  F1 Score
0      LogisticRegression  0.419878   0.127659  0.966023  0.225516
1  DecisionTreeClassifier  0.445457   0.131978  0.957976  0.231995

In [80]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    class_weight="balanced",
    random_state=42
)
test_model(rf, X_train, X_test, y_train, y_test, threshold=0.19)

============================
RandomForestClassifier
============================
Confusion Matrix:
TP=5375, FN=217, FP=34715, TN=23652
Recall = 0.9611945636623748

                    Model  Accuracy  Precision    Recall  F1 Score
0      LogisticRegression  0.419878   0.127659  0.966023  0.225516
1  RandomForestClassifier  0.453838   0.134073  0.961195  0.235322
2  DecisionTreeClassifier  0.445457   0.131978  0.957976  0.231995

In [81]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()
test_model(gb, X_train, X_test, y_train, y_test,threshold=0.19)

============================
GradientBoostingClassifier
============================
Confusion Matrix:
TP=2836, FN=2756, FP=6503, TN=51864
Recall = 0.5071530758226037

                        Model  Accuracy  Precision    Recall  F1 Score
0          LogisticRegression  0.419878   0.127659  0.966023  0.225516
1      RandomForestClassifier  0.453838   0.134073  0.961195  0.235322
2      DecisionTreeClassifier  0.445457   0.131978  0.957976  0.231995
3  GradientBoostingClassifier  0.855235   0.303673  0.507153  0.379881

In [82]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    eval_metric="logloss",
    max_depth=4,
    n_estimators=200,
    learning_rate=0.1
)
test_model(xgb, X_train, X_test, y_train, y_test, threshold=0.19)

============================
XGBClassifier
============================
Confusion Matrix:
TP=2790, FN=2802, FP=6339, TN=52028
Recall = 0.4989270386266094

                        Model  Accuracy  Precision    Recall  F1 Score
0          LogisticRegression  0.419878   0.127659  0.966023  0.225516
1      RandomForestClassifier  0.453838   0.134073  0.961195  0.235322
2      DecisionTreeClassifier  0.445457   0.131978  0.957976  0.231995
3  GradientBoostingClassifier  0.855235   0.303673  0.507153  0.379881
4               XGBClassifier  0.857080   0.305619  0.498927  0.379050

In [16]:
log_reg = LogisticRegression(
    class_weight="balanced",
    max_iter=5000,
    C=0.1,
    penalty="l2",
    solver="liblinear"
)

# Function to get best threshold

In [17]:
import numpy as np
import pandas as pd
from sklearn.metrics import recall_score, precision_score, confusion_matrix

def threshold_sweep(model, X_train, X_test, y_train, y_test, thresholds=None):
    
    if thresholds is None:
        thresholds = np.arange(0.01, 1.0, 0.01)
    
    pipe = Pipeline([
        ("prep", preprocessor),
        ("model", model)
    ])
    
    pipe.fit(X_train, y_train)
    probs = pipe.predict_proba(X_test)[:, 1]

    results = []

    for t in thresholds:
        preds = (probs >= t).astype(int)
        
        tn, fp, fn, tp = confusion_matrix(y_test, preds).ravel()
        
        results.append({
            "Threshold": t,
            "Recall": tp / (tp + fn),
            "Precision": tp / (tp + fp) if (tp+fp)>0 else 0,
            "False Negatives": fn,
            "False Positives": fp,
            "True Positives": tp,
            "True Negatives": tn
        })

    df = pd.DataFrame(results)
    return df

In [18]:
results_df = threshold_sweep(
    log_reg, 
    X_train, X_test, 
    y_train, y_test
)

In [51]:
best = results_df[(results_df["Recall"] >= 0.96)].sort_values("False Positives")
best.head()

,Threshold,Recall,Precision,False Negatives,False Positives,True Positives,True Negatives
18,0.19,0.962983,0.133121,207,35067,5385,23300
17,0.18,0.966202,0.131084,189,35815,5403,22552
16,0.17,0.967990,0.128694,179,36648,5413,21719
15,0.16,0.971745,0.125810,158,37758,5434,20609
14,0.15,0.974249,0.123102,144,38808,5448,19559

# Use Predicted Probability AS the Regression Target

In [ ]:
# ===============================
# 1. Imports
# ===============================
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# ===============================
# 2. Load your dataset
# ===============================
# Replace with your actual dataset path
data = pd.read_csv("./data/heart_2020_cleaned.csv")


X = data.drop('HeartDisease', axis=1)
y = data['HeartDisease']

# ===============================
# 3. Train/test split
# ===============================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# ===============================
# 4. Preprocessing
# ===============================
# Identify numeric and categorical features
X_num = X_train.select_dtypes(include='number')
X_cat = X_train.select_dtypes(exclude='number')

# Categorical columns
cat_cols = X_cat.columns

# Numeric columns (all others)
num_cols = X_num.columns

# Numeric pipeline
num_pipe = Pipeline([
    ("scaler", StandardScaler())
])

# Categorical pipeline
cat_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

# Combine into preprocessor
preprocessor = ColumnTransformer([
    ("num", num_pipe, num_cols),
    ("cat", cat_pipe, cat_cols)
])

# ===============================
# 5. Logistic Regression Classifier
# ===============================
log_reg = LogisticRegression(
    class_weight="balanced",
    max_iter=5000,
    C=0.1,
    penalty="l2",
    solver="liblinear"
)

pipe_clf = Pipeline([
    ("prep", preprocessor),
    ("model", log_reg)
])

pipe_clf.fit(X_train, y_train)

# Predicted probabilities (risk scores)
train_probs = pipe_clf.predict_proba(X_train)[:, 1]
test_probs = pipe_clf.predict_proba(X_test)[:, 1]

# ===============================
# 6. Regression Model to Predict Risk Scores
# ===============================
y_train_reg = train_probs
y_test_reg = test_probs

reg_model = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

pipe_reg = Pipeline([
    ("prep", preprocessor),
    ("reg", reg_model)
])

pipe_reg.fit(X_train, y_train_reg)

# Predict risk scores on test set
risk_pred = pipe_reg.predict(X_test)

# ===============================
# 7. Evaluate Regression
# ===============================
print("MAE:", mean_absolute_error(y_test_reg, risk_pred))
print("R²:", r2_score(y_test_reg, risk_pred))
print("Correlation:", np.corrcoef(y_test_reg, risk_pred)[0,1])

# ===============================
# 8. Convert to Risk Percentage & Category
# ===============================
# Convert probability to percentage
risk_percentage = risk_pred * 100

# Define risk categories
def get_risk_category(prob):
    if prob < 0.2:
        return "Low"
    elif prob < 0.5:
        return "Moderate"
    elif prob < 0.8:
        return "High"
    else:
        return "Very High"

risk_category = [get_risk_category(p) for p in risk_pred]

# Combine into a DataFrame for display
risk_results = pd.DataFrame({
    "Predicted Probability": risk_pred,
    "Risk Percentage": risk_percentage,
    "Risk Category": risk_category
})

# Show first few results
risk_results.head()

MAE: 0.05709478120761218
R²: 0.9043547502405335
Correlation: 0.9510077703242301
   Predicted Probability  Risk Percentage Risk Category
0               0.577631        57.763136          High
1               0.545079        54.507918          High
2               0.101797        10.179681           Low
3               0.818837        81.883745     Very High
4               0.169658        16.965776           Low

In [33]:
risk_results.head(10)

   Predicted Probability  Risk Percentage Risk Category
0               0.577631        57.763136          High
1               0.545079        54.507918          High
2               0.101797        10.179681           Low
3               0.818837        81.883745     Very High
4               0.169658        16.965776           Low
5               0.513815        51.381452          High
6               0.419885        41.988451      Moderate
7               0.438661        43.866087      Moderate
8               0.130849        13.084892           Low
9               0.096451         9.645107           Low